-- Up
-- Mock data generated using Mockaroo.com
INSERT INTO Suggestions (content, author, created_at) VALUES ('Suspendisse potenti.', 'Aime Pecht', '2025-02-02T06:18:36Z');
INSERT INTO Suggestions (content, author, created_at) VALUES ('Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', 'Kristy Romaynes', '2025-02-02T01:30:23Z');
INSERT INTO Suggestions (content, author, created_at) VALUES ('Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 'Ezechiel MacMillan', '2025-02-04T17:41:31Z');
INSERT INTO Suggestions (content, author, created_at) VALUES ('Sed vel enim sit amet nunc viverra dapibus.', 'Lennard Whitman', '2025-02-05T19:18:01Z');
INSERT INTO Suggestions (content, author, created_at) VALUES ('Etiam pretium iaculis justo.', 'Gerhardt Cooke', '2025-02-06T00:35:15Z');
INSERT INTO Suggestions (content, author, created_at) VALUES ('Aenean lectus.', 'Odele Guiducci', '2025-02-07T01:51:03Z');
INSERT INTO Suggestions (content, author, created_at) VALUES ('Ut tellus.', 'West Grimoldby', '2025-02-06T21:28:15Z');
INSERT INTO Suggestions (content, author, created_at) VALUES ('Pellentesque viverra pede ac diam.', 'Charmain Derx', '2025-02-02T08:44:59Z');
INSERT INTO Suggestions (content, author, created_at) VALUES ('Integer tincidunt ante vel ipsum.', 'Jobi Durbann', '2025-02-03T04:11:06Z');
INSERT INTO Suggestions (content, author, created_at) VALUES ('Praesent lectus.', 'Stesha Lanon', '2025-02-04T22:21:32Z');

INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 'Virginia Ead', '2025-02-09T17:21:20Z', 8);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', 'Cairistiona Rann', '2025-02-07T15:46:10Z', 10);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 'Gilbertina Currier', '2025-02-05T08:59:04Z', 3);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Donec vitae nisi.', 'Truman Rabat', '2025-02-08T12:57:26Z', 9);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.', 'Branden Balmer', '2025-02-08T10:43:38Z', 10);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 'Eugene Giacopini', '2025-02-07T22:16:05Z', 8);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Phasellus in felis.', 'Dominique Pearmine', '2025-02-07T06:27:32Z', 8);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Cras non velit nec nisi vulputate nonummy.', 'Frasier Trembley', '2025-02-05T06:45:24Z', 3);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 'Vi Ridge', '2025-02-09T03:10:14Z', 7);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Suspendisse potenti.', 'Ethelind Roslen', '2025-02-09T22:51:27Z', 9);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Proin at turpis a pede posuere nonummy. Integer non velit.', 'Herc Tague', '2025-02-05T10:22:16Z', 2);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio.', 'Chane Broadwell', '2025-02-06T22:13:44Z', 7);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Donec dapibus. Duis at velit eu est congue elementum.', 'Erastus Caton', '2025-02-09T16:36:08Z', 4);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 'Peta Lunck', '2025-02-08T00:34:18Z', 10);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 'Coreen Rottger', '2025-02-08T14:28:34Z', 2);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', 'Dulce Sidlow', '2025-02-05T06:08:20Z', 10);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Suspendisse potenti.', 'Clayborne Iscowitz', '2025-02-08T18:52:35Z', 8);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Praesent blandit. Nam nulla.', 'Aurora Horlock', '2025-02-05T07:25:15Z', 1);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'Findlay Lampitt', '2025-02-08T21:12:16Z', 1);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 'Feliks MacVean', '2025-02-07T02:01:58Z', 4);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Nulla suscipit ligula in lacus.', 'Lucky O''Caherny', '2025-02-09T13:05:09Z', 9);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.', 'Edeline McCulloch', '2025-02-09T23:35:34Z', 6);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.', 'Roxane McKendo', '2025-02-06T11:39:55Z', 5);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 'Nat Yorke', '2025-02-08T19:21:59Z', 9);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Nunc purus. Phasellus in felis.', 'Zahara Heavy', '2025-02-05T18:29:41Z', 2);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', 'Mareah Jeannon', '2025-02-06T04:15:14Z', 3);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'Waldon Canet', '2025-02-05T09:26:41Z', 6);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 'Jennie Damarell', '2025-02-06T20:33:02Z', 8);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Maecenas rhoncus aliquam lacus.', 'Cleopatra McCane', '2025-02-09T08:57:56Z', 2);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis.', 'Cinnamon Wennington', '2025-02-09T05:29:48Z', 9);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.', 'Alanna Seeger', '2025-02-09T03:56:54Z', 5);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 'Vernor O''Regan', '2025-02-09T16:15:39Z', 7);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'Tabbitha Paulsson', '2025-02-09T01:56:10Z', 6);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Suspendisse accumsan tortor quis turpis. Sed ante.', 'Octavia Beany', '2025-02-08T03:43:36Z', 1);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', 'Nata Basler', '2025-02-09T21:25:59Z', 2);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 'Sasha Facey', '2025-02-07T05:30:51Z', 9);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 'Yale Woolens', '2025-02-08T22:50:01Z', 9);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla.', 'Elie Blessed', '2025-02-05T20:39:04Z', 10);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy.', 'Ruthie Rawstron', '2025-02-09T12:28:29Z', 2);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Nulla tempus.', 'Marybeth Proven', '2025-02-08T16:46:38Z', 6);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 'Alejandra Hay', '2025-02-09T05:22:00Z', 7);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'Beniamino Maass', '2025-02-08T10:51:52Z', 2);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.', 'Rachael Morgans', '2025-02-08T06:07:20Z', 5);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.', 'Ericha Marcome', '2025-02-06T08:59:02Z', 1);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Maecenas tincidunt lacus at velit.', 'Carmina Fears', '2025-02-07T22:46:22Z', 6);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.', 'Nertie Rosenschein', '2025-02-09T07:44:07Z', 6);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Donec semper sapien a libero.', 'Harlin Reames', '2025-02-07T03:00:56Z', 3);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'Elissa O''Criane', '2025-02-05T03:15:06Z', 3);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Nulla nisl.', 'Horace Donnison', '2025-02-06T09:19:07Z', 7);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Fusce consequat. Nulla nisl.', 'Donella D''Angeli', '2025-02-05T17:57:56Z', 10);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Nulla ut erat id mauris vulputate elementum.', 'Mendel Kendall', '2025-02-09T19:14:53Z', 7);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', 'Abigail Girodier', '2025-02-09T18:41:37Z', 2);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Suspendisse potenti.', 'Clyde Tubbles', '2025-02-08T12:51:45Z', 5);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc.', 'Egan Sarton', '2025-02-08T14:14:09Z', 5);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 'Friedrich Flippini', '2025-02-06T16:17:32Z', 6);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.', 'Izak Tuminelli', '2025-02-05T22:41:26Z', 2);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Fusce consequat.', 'Jackie Tester', '2025-02-07T23:59:03Z', 6);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 'Raine Greenroad', '2025-02-07T17:49:37Z', 6);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.', 'Eugine Roostan', '2025-02-08T09:00:55Z', 4);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 'Alaric Shorthill', '2025-02-08T17:53:17Z', 2);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('In congue. Etiam justo.', 'Sanford Dollar', '2025-02-06T06:45:29Z', 1);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Quisque ut erat.', 'Esme Cawse', '2025-02-07T23:29:13Z', 8);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna.', 'Cash Farnhill', '2025-02-06T07:57:32Z', 10);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('In congue. Etiam justo. Etiam pretium iaculis justo.', 'Jonie Toffolo', '2025-02-09T11:43:18Z', 1);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Vivamus in felis eu sapien cursus vestibulum.', 'Barny Bisset', '2025-02-08T15:51:48Z', 8);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 'Joela Pickavant', '2025-02-08T18:08:14Z', 10);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Ut tellus. Nulla ut erat id mauris vulputate elementum.', 'Abe Irvine', '2025-02-07T06:06:05Z', 2);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.', 'Jeddy de Pinna', '2025-02-09T01:12:23Z', 1);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.', 'Phoebe Bramstom', '2025-02-06T12:47:00Z', 5);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Nulla ut erat id mauris vulputate elementum.', 'Brynne Despenser', '2025-02-05T14:45:26Z', 9);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 'Kass Boss', '2025-02-09T15:15:45Z', 4);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Nulla nisl. Nunc nisl.', 'Neall Tofanini', '2025-02-09T03:23:39Z', 2);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 'Ava Blackader', '2025-02-07T04:10:02Z', 6);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.', 'Wilbur Chamney', '2025-02-08T22:26:20Z', 8);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', 'Tadeas Caldera', '2025-02-09T18:40:07Z', 4);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.', 'Evy Le Grove', '2025-02-06T10:49:11Z', 5);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 'Brett Bellhanger', '2025-02-07T06:03:18Z', 8);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Etiam vel augue. Vestibulum rutrum rutrum neque.', 'Keith Thormwell', '2025-02-05T04:52:22Z', 5);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Morbi vel lectus in quam fringilla rhoncus.', 'Bill Mennithorp', '2025-02-09T06:07:19Z', 1);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Duis bibendum. Morbi non quam nec dui luctus rutrum.', 'Freddie Baal', '2025-02-07T23:55:54Z', 8);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 'Claudian Gippes', '2025-02-07T04:26:20Z', 6);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 'Tyrone Ciubutaro', '2025-02-06T08:34:22Z', 5);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.', 'Sherman Speir', '2025-02-07T05:06:13Z', 10);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.', 'Tracey Stang-Gjertsen', '2025-02-05T13:58:47Z', 7);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 'Lanie Reddell', '2025-02-06T19:38:40Z', 8);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Nulla tellus. In sagittis dui vel nisl. Duis ac nibh.', 'Avril Sadgrove', '2025-02-09T06:26:49Z', 7);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 'Duane Enriques', '2025-02-06T23:23:46Z', 2);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.', 'Samara Kemell', '2025-02-06T18:50:40Z', 3);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Nulla suscipit ligula in lacus.', 'Travis Summerell', '2025-02-06T00:53:46Z', 9);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Maecenas pulvinar lobortis est.', 'Glori Moreland', '2025-02-06T22:36:38Z', 7);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Nunc purus. Phasellus in felis. Donec semper sapien a libero.', 'Aldridge Sangar', '2025-02-07T15:05:11Z', 5);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 'Catlee Alabastar', '2025-02-05T18:42:40Z', 6);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 'Toddie Beatson', '2025-02-06T21:01:28Z', 8);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'Olvan Godthaab', '2025-02-05T03:51:51Z', 4);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna.', 'Brennan Bjorkan', '2025-02-06T11:34:33Z', 8);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Morbi a ipsum.', 'Waldemar Tapper', '2025-02-06T15:32:02Z', 6);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Mauris ullamcorper purus sit amet nulla.', 'Filbert Andover', '2025-02-08T16:29:33Z', 3);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.', 'Daisey Walkden', '2025-02-08T12:03:48Z', 4);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.', 'Berna Terbrug', '2025-02-05T01:34:39Z', 6);
INSERT INTO Comments (content, author, created_at, suggestion_id) VALUES ('Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 'Golda Jime', '2025-02-09T09:48:05Z', 8);

-- Down
DELETE FROM Comments;
DELETE FROM Suggestions;